### ISSUE TITLE
Header issues

### ISSUE THREAD

**Issue by Fraudoctor** [dhackner/bec#6]
Just says Transfer throughout on the Expo App.

**Comment by dhackner** [comment]
Can you reopen the app? This should be fixed

**Comment by Fraudoctor** [comment]
Fixed as of this AM.

However, once in a section (ie Airway, Breathing) there is a header "Airway" button that functions like the lower "Back" button next to the work "Airway".
![img_23a2abd98800-1](https://user-images.githubusercontent.com/16942575/41674477-f60bf49a-7474-11e8-9c74-b951a54cf14d.jpeg)

**Comment by dhackner** [comment]
Fixed in 1d109f0085ea5293f5094c695e832adb94172a43
